name: Terraform CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.5
    - name: Terraform fmt
      run: terraform fmt -check
      working-directory: environments/demo
    - name: Terraform Init
      run: terraform init
      working-directory: environments/demo
    - name: Terraform Validate
      run: terraform validate
      working-directory: environments/demo
    - name: Terraform Plan
      run: terraform plan -out=plan.tfout
      working-directory: environments/demo
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
